### ISSUE TITLE
TypeError: Collection.helpers is not a function

### ISSUE THREAD

**Issue by mcorbelli** [dburles/meteor-collection-helpers#91]
# Issue: `helpers is not a function` in `meteor-collection-helpers` after upgrading to Meteor 3.2

## Description

After upgrading my app to **Meteor 3.2**, I encountered the following error when trying to call `helpers` on a collection:

```
TypeError: EventSchedulingDB.helpers is not a function
```

## Stack Trace

```
TypeError: EventSchedulingDB.helpers is not a function
    at module.wrapAsync.self (imports/database/event_scheduling.db.js:30:19)
    ...
```

## Environment

- Meteor version: **3.2**
- meteor-collection-helpers version: **2.0.0**
- Node.js version: 22.14.0 (as used internally by Meteor 3.2)

## Additional Context

Before upgrading to Meteor 3.2, the same code was working correctly. I suspect this issue may be related to internal changes in how collections are implemented or managed in Meteor 3.x.

Here’s a sample of what I’m doing:

```js
import { Mongo } from "meteor/mongo";
const EventSchedulingDB = new Mongo.Collection("event_scheduling");

EventSchedulingDB.helpers({
  getName() {
    return this.name;
  }
});
```

After upgrading, the `.helpers` method is not recognized.

## Expected Behavior

The `helpers` method should be available on Mongo collections after importing `meteor-collection-helpers`.

## Actual Behavior

Calling `.helpers()` throws a `TypeError` because it is not a function.

## Request

Could you please confirm whether the `meteor-collection-helpers` package is compatible with Meteor 3.2? If not, is there a plan to update the package or an alternative you recommend?

**Comment by dburles** [comment]
Thanks @mcorbelli I'll take a look into this.

**Comment by dburles** [comment]
I've just tested Meteor 3.2.2 on a new app (`meteor create x`) and it's working. There's possibly something else amiss? Double check the package is installed.

**Comment by mcorbelli** [comment]
Hi, I double-checked and I was indeed using version 1.0.0 of the package. After upgrading to 2.0.0, I’m now getting the error:
.helpers is not a function.

I haven’t changed anything else in my code apart from the package update, so I’m not sure how to fix this. Any ideas on what might be causing it or what changed in the usage between versions?

These are the packages installed in my project:

BEFORE UPDATE

`
meteor-base@1.5.2
mobile-experience@1.1.2
mongo@2.1.0
reactive-var@1.0.13
standard-minifier-css@1.9.3
standard-minifier-js@3.0.0
es5-shim@4.8.1
ecmascript@0.16.10
typescript@5.6.3
shell-server@0.6.1
hot-module-replacement@0.5.4
email@3.1.2
accounts-password@3.0.3
alanning:roles
aldeed:collection2
jam:method
matb33:collection-hooks@2.0.0-rc.4
jam:mongo-transactions
react-meteor-data
static-html@1.4.0
simple:rest
dburles:collection-helpers
tunguska:reactive-aggregate
`

UFTER UPDATE

`
meteor-base@1.5.2
mobile-experience@1.1.2
mongo@2.1.0
reactive-var@1.0.13
standard-minifier-css@1.9.3
standard-minifier-js@3.0.0
es5-shim@4.8.1
ecmascript@0.16.10
typescript@5.6.3
shell-server@0.6.1
hot-module-replacement@0.5.4
email@3.1.2
accounts-password@3.0.3
alanning:roles@4.0.0
aldeed:collection2@4.0.4
jam:method@1.9.1
matb33:collection-hooks@2.0.0
jam:mongo-transactions@1.2.0
react-meteor-data@4.0.0
static-html@1.4.0
simple:rest@1.2.1
dburles:collection-helpers@2.0.0
tunguska:reactive-aggregate@2.0.2
`

Thanks in advance!

**Comment by dburles** [comment]
I would just try to create a fresh  Meteor 3.0 app and confirm it's working there then try to debug the problematic app piece by piece.

**Comment by mcorbelli** [comment]
Sorry for the delayed response.
I tried creating a new Meteor project from scratch and installed two packages: "aldeed:collection2" and "matb33:collection-hooks". However, I’m encountering the exact same error as before.

The error appears immediately:

TypeError: LinksCollection.helpers is not a function

I haven’t changed anything else in the default Meteor starter project, except installing those packages and adding some code in the links.js file (which I’ve attached).

![Image](https://github.com/user-attachments/assets/33397526-cd19-4aff-b86a-a22fb9d4cbaa)

**Comment by dburles** [comment]
Interesting. Can you narrow it down to either one of those packages?

**Comment by redspear** [comment]
If you're using custom packages, make sure to include dburles:collection-helpers in the api.use array. Fixed it for my case.

`Package.onUse((api) => {
	api.versionsFrom(['1.10', '2.3', '3.0']);
	api.use(['ecmascript', 'mongo', 'dburles:collection-helpers']);
	api.mainModule('lib/server.js', 'server');
});`
